const router = require('koa-router')()
const project = require("./project/project")
const time = require("./time/time")
const know = require("./konwledge/knowledge")
const common =require('./single/common')
const security =require('./security/security')
const user = require("./person/users")
// const Time = require("../../../module/pim/time/time")
router.use("/user",user)
// router.get("/getTime",Time.getTime)
router.use("/project",project)
router.use("/time",time)
router.use("/knowledge",know)
router.use("/common",common)
router.use("/security",security)

module.exports = router.routes()